# Generated by Django 4.0.4 on 2022-05-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_remove_propietario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='condicionesPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEscrituracion', models.DateField()),
                ('montoFinanciamiento', models.FloatField()),
                ('plazo', models.IntegerField()),
                ('tasaInteres', models.FloatField()),
                ('cuotaKi', models.FloatField()),
                ('comisionCuota', models.FloatField()),
                ('mantenimientoCuota', models.FloatField()),
                ('multaMantenimiento', models.FloatField()),
                ('multaFinanciamiento', models.FloatField()),
                ('detalleVenta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa')),
            ],
        ),
        migrations.CreateModel(
            name='tablaAmortizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicionesPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.condicionespago')),
            ],
        ),
        migrations.CreateModel(
            name='resumenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaUltimoPago', models.DateField()),
                ('fechaUltimoCorte', models.DateField()),
                ('saldoCapital', models.FloatField()),
                ('fechaCancelado', models.DateField()),
                ('descuentoPP', models.FloatField()),
                ('prima', models.FloatField()),
                ('abonosCapital', models.FloatField()),
                ('abonosComision', models.FloatField()),
                ('abonosRecargo', models.FloatField()),
                ('abonosOtros', models.FloatField()),
                ('abonosIntereses', models.FloatField()),
                ('abonosMantenimiento', models.FloatField()),
                ('condicionesPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.condicionespago')),
            ],
        ),
        migrations.CreateModel(
            name='cuotaAmortizacion',
            fields=[
                ('numeroCuota', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('diasInteres', models.IntegerField()),
                ('montoCancelado', models.FloatField()),
                ('tasaInteres', models.FloatField()),
                ('interesGenerado', models.FloatField()),
                ('interesPagado', models.FloatField()),
                ('comision', models.FloatField()),
                ('mantenimiento', models.FloatField()),
                ('subTotal', models.FloatField()),
                ('abonoCapital', models.FloatField()),
                ('saldoCapital', models.FloatField()),
                ('saldoInteres', models.FloatField()),
                ('tablaAmortizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.tablaamortizacion')),
            ],
        ),
    ]
