# Generated by Django 4.0.4 on 2022-05-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_propietario_telefonocasa_and_more'),
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumenpago',
            name='condicionesPago',
        ),
        migrations.RemoveField(
            model_name='tablaamortizacion',
            name='condicionesPago',
        ),
        migrations.AddField(
            model_name='resumenpago',
            name='detalleVenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa'),
        ),
        migrations.AddField(
            model_name='tablaamortizacion',
            name='detalleVenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa'),
        ),
        migrations.CreateModel(
            name='estadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalleVenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa')),
            ],
        ),
        migrations.CreateModel(
            name='cuotaEstadoCuenta',
            fields=[
                ('numeroCuota', models.IntegerField(primary_key=True, serialize=False)),
                ('diasInteres', models.IntegerField()),
                ('tasaInteres', models.FloatField()),
                ('interesGenerado', models.FloatField()),
                ('interesPagado', models.FloatField()),
                ('subTotal', models.FloatField()),
                ('abonoCapital', models.FloatField()),
                ('saldoCapital', models.FloatField()),
                ('saldoInteres', models.FloatField()),
                ('estadoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.estadocuenta')),
            ],
        ),
    ]
