# Generated by Django 4.0.4 on 2022-06-02 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_detalleventa_descuento_and_more'),
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuenta',
            name='detalleVenta',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumenpago',
            name='detalleVenta',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablaamortizacion',
            name='detalleVenta',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa'),
            preserve_default=False,
        ),
    ]
