# Generated by Django 4.0.4 on 2022-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionespago',
            name='cuotaKi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
