# Generated by Django 4.0.4 on 2022-07-21 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotaamortizacion',
            name='mantenimiento',
        ),
        migrations.RemoveField(
            model_name='estadocuenta',
            name='cuotaAmortizacion',
        ),
        migrations.RemoveField(
            model_name='estadocuenta',
            name='detalleVenta',
        ),
        migrations.AddField(
            model_name='condicionespago',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='condicionesPago',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.condicionespago'),
            preserve_default=False,
        ),
    ]
