# Generated by Django 4.0.4 on 2022-05-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_remove_pagomantenimiento_numerocuotaestadocuenta_and_more'),
        ('monitoreo', '0002_remove_resumenpago_condicionespago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotaamortizacion',
            name='tablaAmortizacion',
        ),
        migrations.RemoveField(
            model_name='cuotaestadocuenta',
            name='estadoCuenta',
        ),
        migrations.RemoveField(
            model_name='estadocuenta',
            name='detalleVenta',
        ),
        migrations.RemoveField(
            model_name='resumenpago',
            name='detalleVenta',
        ),
        migrations.RemoveField(
            model_name='tablaamortizacion',
            name='detalleVenta',
        ),
        migrations.DeleteModel(
            name='condicionesPago',
        ),
        migrations.DeleteModel(
            name='cuotaAmortizacion',
        ),
        migrations.DeleteModel(
            name='cuotaEstadoCuenta',
        ),
        migrations.DeleteModel(
            name='estadoCuenta',
        ),
        migrations.DeleteModel(
            name='resumenPago',
        ),
        migrations.DeleteModel(
            name='tablaAmortizacion',
        ),
    ]
