# Generated by Django 4.0.4 on 2022-07-21 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_remove_cuotaamortizacion_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='fechaRegistro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='nombre',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
