# Generated by Django 4.0.4 on 2022-07-19 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoreo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prima',
            fields=[
                ('numeroReciboPrima', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('conceptoPrima', models.CharField(max_length=50)),
                ('detalleVenta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa')),
                ('usuarioCreacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_prima', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pagoMantenimiento',
            fields=[
                ('numeroReciboMantenimiento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaUltimoMtto', models.DateField(blank=True)),
                ('abono', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('fechaUltimoRecargo', models.DateField(blank=True)),
                ('saldoRecargo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('mantenimiento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recargoMtto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('conceptoOtros', models.CharField(blank=True, default='', max_length=100)),
                ('montoOtros', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('conceptoDescuento', models.CharField(blank=True, default='', max_length=100)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('estadoCuenta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.estadocuenta')),
                ('usuarioCreacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_mantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pagoFinanciamiento',
            fields=[
                ('numeroReciboFinanciamiento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recargoFinanciamiento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('conceptoOtros', models.CharField(blank=True, default='', max_length=100)),
                ('montoOtros', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('conceptoDescuento', models.CharField(blank=True, default='', max_length=100)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('estadoCuenta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.estadocuenta')),
                ('usuarioCreacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_financiamiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pagoCuotaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroReciboMantenimiento', models.CharField(max_length=30)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaPago', models.DateField()),
                ('fechaCorte', models.DateField()),
                ('concepto', models.CharField(blank=True, default='', max_length=100)),
                ('mantenimiento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recargo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('otros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estadoCuenta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.estadocuenta')),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipoPago', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Banco')])),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('fechaPago', models.DateField()),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('cuentaBancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentabancaria')),
                ('pagoFinanciamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagofinanciamiento')),
                ('pagoMantenimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagomantenimiento')),
                ('prima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.prima')),
            ],
        ),
    ]
