# Generated by Django 4.0.4 on 2022-07-07 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoreo', '0001_initial'),
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomantenimiento',
            name='numeroCuotaEstadoCuenta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.cuotaestadocuenta'),
        ),
        migrations.AddField(
            model_name='pagomantenimiento',
            name='usuarioCreacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_mantenimiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagofinanciamiento',
            name='numeroCuotaEstadoCuenta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.cuotaestadocuenta'),
        ),
        migrations.AddField(
            model_name='pagofinanciamiento',
            name='usuarioCreacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_financiamiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='cuentaBancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagoFinanciamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagofinanciamiento'),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagoMantenimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagomantenimiento'),
        ),
        migrations.AddField(
            model_name='pago',
            name='prima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.prima'),
        ),
    ]
