# Generated by Django 4.0.4 on 2022-06-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
