# Generated by Django 4.0.4 on 2022-07-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocuotamantenimiento',
            name='rubro',
        ),
    ]
