# Generated by Django 4.0.4 on 2022-06-07 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofinanciamiento',
            name='tipoPago',
            field=models.CharField(default='aaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagofinanciamiento',
            name='usuarioCreacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagomantenimiento',
            name='tipoPago',
            field=models.CharField(default='aaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagomantenimiento',
            name='usuarioCreacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagofinanciamiento',
            name='conceptoOtros',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagofinanciamiento',
            name='montoOtros',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagomantenimiento',
            name='conceptoOtros',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
