# Generated by Django 4.0.4 on 2022-05-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prima',
            old_name='numeroRecibo',
            new_name='numeroReciboPrima',
        ),
    ]
