# Generated by Django 4.0.4 on 2022-05-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_rename_numerorecibo_prima_numeroreciboprima'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagoFinanciamiento',
            fields=[
                ('numeroReciboFinanciamiento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('monto', models.FloatField()),
                ('mantenimiento', models.FloatField()),
                ('comision', models.FloatField()),
                ('conceptoOtros', models.CharField(max_length=50)),
                ('montoOtros', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='pagoMantenimiento',
            fields=[
                ('numeroReciboMantenimiento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('monto', models.FloatField()),
                ('conceptoOtros', models.CharField(max_length=50)),
                ('montoOtros', models.FloatField()),
            ],
        ),
    ]
