# Generated by Django 4.0.4 on 2022-07-12 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagoCuotaMantenimiento',
            fields=[
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('numeroReciboMantenimiento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fechaCorte', models.DateField()),
                ('rubro', models.CharField(blank=True, default='', max_length=100)),
                ('concepto', models.CharField(blank=True, default='', max_length=100)),
                ('mantenimiento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recargo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('usuarioCreacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_cuotaMantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
