# Generated by Django 4.0.4 on 2022-07-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_pagocuotamantenimiento_concepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuotamantenimiento',
            name='concepto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
