# Generated by Django 4.0.4 on 2022-06-08 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_alter_lote_numerolote_alter_lote_poligono'),
        ('facturacion', '0002_pagofinanciamiento_tipopago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofinanciamiento',
            name='cuentaBancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='pagofinanciamiento',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pagomantenimiento',
            name='cuentaBancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='pagomantenimiento',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prima',
            name='cuentaBancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='prima',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prima',
            name='tipoPago',
            field=models.CharField(default='aaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prima',
            name='usuarioCreacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_prima', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagofinanciamiento',
            name='usuarioCreacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_financiamiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagomantenimiento',
            name='usuarioCreacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_mantenimiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
