# Generated by Django 4.0.4 on 2022-06-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_lote_numerolote_alter_lote_poligono'),
        ('facturacion', '0003_pagofinanciamiento_cuentabancaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagofinanciamiento',
            name='cuentaBancaria',
        ),
        migrations.RemoveField(
            model_name='pagofinanciamiento',
            name='fechaPago',
        ),
        migrations.RemoveField(
            model_name='pagofinanciamiento',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='pagofinanciamiento',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='pagofinanciamiento',
            name='tipoPago',
        ),
        migrations.RemoveField(
            model_name='pagomantenimiento',
            name='cuentaBancaria',
        ),
        migrations.RemoveField(
            model_name='pagomantenimiento',
            name='fechaPago',
        ),
        migrations.RemoveField(
            model_name='pagomantenimiento',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='pagomantenimiento',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='pagomantenimiento',
            name='tipoPago',
        ),
        migrations.RemoveField(
            model_name='prima',
            name='cuentaBancaria',
        ),
        migrations.RemoveField(
            model_name='prima',
            name='fechaPrima',
        ),
        migrations.RemoveField(
            model_name='prima',
            name='montoPrima',
        ),
        migrations.RemoveField(
            model_name='prima',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='prima',
            name='tipoPago',
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('tipoPago', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fechaPago', models.DateField()),
                ('cuentaBancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentabancaria')),
                ('pagoFinanciamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagofinanciamiento')),
                ('pagoMantenimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagomantenimiento')),
                ('prima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.prima')),
            ],
        ),
    ]
