# Generated by Django 4.0.4 on 2022-05-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_pagomantenimiento_numerocuotaestadocuenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagomantenimiento',
            name='numeroCuotaEstadoCuenta',
        ),
        migrations.RemoveField(
            model_name='prima',
            name='detalleVenta',
        ),
        migrations.DeleteModel(
            name='pagoFinanciamiento',
        ),
        migrations.DeleteModel(
            name='pagoMantenimiento',
        ),
        migrations.DeleteModel(
            name='prima',
        ),
    ]
