# Generated by Django 4.0.4 on 2022-06-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_remove_pagofinanciamiento_cuentabancaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipoPago',
            field=models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Banco')]),
        ),
    ]
