# Generated by Django 4.0.4 on 2022-05-31 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0007_propietario_lote_detalleventa_asignacionlote'),
        ('monitoreo', '0004_initial'),
        ('facturacion', '0005_remove_pagomantenimiento_numerocuotaestadocuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='prima',
            fields=[
                ('numeroReciboPrima', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fechaPrima', models.DateField()),
                ('montoPrima', models.FloatField()),
                ('conceptoPrima', models.CharField(max_length=50)),
                ('detalleVenta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa')),
            ],
        ),
        migrations.CreateModel(
            name='pagoMantenimiento',
            fields=[
                ('numeroReciboMantenimiento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('monto', models.FloatField()),
                ('conceptoOtros', models.CharField(max_length=50)),
                ('montoOtros', models.FloatField()),
                ('numeroCuotaEstadoCuenta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.cuotaestadocuenta')),
            ],
        ),
        migrations.CreateModel(
            name='pagoFinanciamiento',
            fields=[
                ('numeroReciboFinanciamiento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('monto', models.FloatField()),
                ('mantenimiento', models.FloatField()),
                ('comision', models.FloatField()),
                ('conceptoOtros', models.CharField(max_length=50)),
                ('montoOtros', models.FloatField()),
                ('numeroCuotaEstadoCuenta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.cuotaestadocuenta')),
            ],
        ),
    ]
