# Generated by Django 4.0.4 on 2022-05-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyectoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyectoTuristico', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nombreProyectoTuristico', 'empresa'],
            },
        ),
        migrations.CreateModel(
            name='cuentaBancaria',
            fields=[
                ('numeroCuentaBancaria', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombreCuentaBancaria', models.CharField(max_length=50)),
                ('tipoCuenta', models.CharField(max_length=30)),
                ('banco', models.CharField(max_length=30)),
                ('proyectoTuristico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proyectoturistico')),
            ],
        ),
    ]
