# Generated by Django 4.0.4 on 2022-06-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precioVenta',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='correoElectronico',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='direccionTrabajo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefonoCasa',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefonoTrabajo',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='trabajo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
