# Generated by Django 4.0.4 on 2022-06-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='areaMCuadrado',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='lote',
            name='areaVCuadrada',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='lote',
            name='identificador',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numeroLote',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='lote',
            name='poligono',
            field=models.CharField(max_length=2),
        ),
    ]
