# Generated by Django 4.0.4 on 2022-07-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacionproyecto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asignacionproyecto',
            name='dui',
            field=models.CharField(default=56560136, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='asignacionproyecto',
            unique_together={('dui', 'proyectoTuristico')},
        ),
    ]
