# Generated by Django 4.0.4 on 2022-06-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='numeroLote',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='poligono',
            field=models.CharField(max_length=5),
        ),
    ]
