# Generated by Django 4.0.4 on 2022-06-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_lote_numerolote_alter_lote_poligono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='areaMtCuadrado',
            new_name='areaMCuadrado',
        ),
    ]
