# Generated by Django 4.0.4 on 2022-06-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_detalleventa_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='areaMCuadrado',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='lote',
            name='areaVCuadrada',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
