# Generated by Django 4.0.4 on 2022-05-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_propietario_alter_proyectoturistico_options_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='id',
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombrePropietario',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
