# Generated by Django 4.0.4 on 2022-06-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_lote_areamcuadrado_alter_lote_areavcuadrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='descuento',
            field=models.CharField(default=0.0, max_length=9),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precioVenta',
            field=models.CharField(default=0.0, max_length=9),
        ),
    ]
