# Generated by Django 4.0.4 on 2022-07-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_propietario_dui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='dui',
            field=models.CharField(max_length=10),
        ),
    ]
