# Generated by Django 4.0.4 on 2022-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_propietario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='telefonoCasa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefonoCelular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefonoTrabajo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
