# Generated by Django 4.0.4 on 2022-06-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_areamtcuadrado_lote_areamcuadrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='identificador',
            field=models.CharField(default='a', max_length=4),
            preserve_default=False,
        ),
    ]
