# Generated by Django 4.0.4 on 2022-06-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_asignacionlote_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='numeroLote',
            field=models.CharField(max_length=2),
        ),
    ]
