# Generated by Django 4.0.4 on 2022-06-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_lote_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='proyectoTuristico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.proyectoturistico'),
        ),
    ]
