# Generated by Django 4.0.4 on 2022-05-31 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_propietario_telefonocasa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='areaMtCuadrado',
        ),
    ]
