# Generated by Django 4.0.4 on 2022-05-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_remove_cuotaamortizacion_tablaamortizacion_and_more'),
        ('facturacion', '0005_remove_pagomantenimiento_numerocuotaestadocuenta_and_more'),
        ('inventario', '0005_remove_lote_areamtcuadrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='proyectoTuristico',
        ),
        migrations.DeleteModel(
            name='asignacionLote',
        ),
        migrations.DeleteModel(
            name='detalleVenta',
        ),
        migrations.DeleteModel(
            name='lote',
        ),
        migrations.DeleteModel(
            name='propietario',
        ),
    ]
