# Generated by Django 4.0.4 on 2022-05-31 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_detalleventa_lote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('nombrePropietario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('trabajo', models.CharField(blank=True, max_length=30, null=True)),
                ('direccionTrabajo', models.CharField(blank=True, max_length=30, null=True)),
                ('telefonoTrabajo', models.IntegerField(blank=True, null=True)),
                ('telefonoCasa', models.IntegerField(blank=True, null=True)),
                ('telefonoCelular', models.IntegerField()),
                ('correoElectronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('eliminado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='lote',
            fields=[
                ('matriculaLote', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numeroLote', models.IntegerField()),
                ('poligono', models.CharField(max_length=50)),
                ('areaMtCuadrado', models.FloatField()),
                ('areaVCuadrada', models.FloatField()),
                ('proyectoTuristico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proyectoturistico')),
            ],
        ),
        migrations.CreateModel(
            name='detalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioVenta', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lote')),
            ],
        ),
        migrations.CreateModel(
            name='asignacionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalleVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleventa')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.propietario')),
            ],
            options={
                'unique_together': {('propietario', 'detalleVenta')},
            },
        ),
    ]
