# Generated by Django 4.0.4 on 2022-06-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_lote_identificador_condicionpago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='condicionPago',
        ),
    ]
