# Generated by Django 4.0.4 on 2022-06-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_propietario_lote_detalleventa_asignacionlote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='direccionTrabajo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefonoCasa',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefonoCelular',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefonoTrabajo',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='trabajo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
