# Generated by Django 4.0.4 on 2022-06-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_propietario_direcciontrabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='dui',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
